# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': '校区表', 'verbose_name_plural': '校区表'},
        ),
        migrations.AlterModelOptions(
            name='classlist',
            options={'verbose_name': '班级表', 'verbose_name_plural': '班级表'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程表', 'verbose_name_plural': '课程表'},
        ),
        migrations.AlterModelOptions(
            name='courserecord',
            options={'verbose_name': '上课记录', 'verbose_name_plural': '上课记录'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客户信息表', 'verbose_name_plural': '客户信息表'},
        ),
        migrations.AlterModelOptions(
            name='customerfollowup',
            options={'verbose_name': '客户跟进表', 'verbose_name_plural': '客户跟进表'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': '报名表', 'verbose_name_plural': '报名表'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': '交费记录表', 'verbose_name_plural': '交费记录表'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '角色表', 'verbose_name_plural': '角色表'},
        ),
        migrations.AlterModelOptions(
            name='studyrecode',
            options={'verbose_name': '学习记录表', 'verbose_name_plural': '学习记录表'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签表', 'verbose_name_plural': '标签表'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '账户表', 'verbose_name_plural': '账户表'},
        ),
        migrations.AlterUniqueTogether(
            name='studyrecode',
            unique_together=set([('student', 'course_recode')]),
        ),
    ]
