# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20170703_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='menus',
            field=models.ManyToManyField(to='crm.Menu'),
        ),
    ]
