# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20170703_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '菜单表', 'verbose_name_plural': '菜单表'},
        ),
        migrations.AlterField(
            model_name='classlist',
            name='branch',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='crm.Branch', verbose_name='校区'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='course',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='crm.Course'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='teachers',
            field=models.ManyToManyField(db_constraint=False, to='crm.UserProfile'),
        ),
        migrations.AlterField(
            model_name='courserecord',
            name='from_class',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='crm.ClassList', verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='courserecord',
            name='tercher',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='consult_course',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Course', verbose_name='咨询课程'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='consultant',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tags',
            field=models.ManyToManyField(blank=True, db_constraint=False, to='crm.Tag'),
        ),
        migrations.AlterField(
            model_name='customerfollowup',
            name='consultant',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile'),
        ),
        migrations.AlterField(
            model_name='customerfollowup',
            name='customer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='crm.Customer'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='consultant',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile', verbose_name='课程顾问'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='customer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='crm.Customer'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_class',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='crm.ClassList', verbose_name='所报班级'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='consultant',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='crm.Course', verbose_name='所报课程'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='crm.Customer'),
        ),
        migrations.AlterField(
            model_name='role',
            name='menus',
            field=models.ManyToManyField(blank=True, db_constraint=False, to='crm.Menu'),
        ),
        migrations.AlterField(
            model_name='studyrecode',
            name='course_recode',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='crm.CourseRecord'),
        ),
        migrations.AlterField(
            model_name='studyrecode',
            name='student',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='crm.Enrollment'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, db_constraint=False, null=True, to='crm.Role'),
        ),
    ]
