# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20170707_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, db_constraint=False, to='crm.Role'),
        ),
    ]
