# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20170713_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '已报名'), (1, '未报名')], default=0),
            preserve_default=False,
        ),
    ]
